server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-microservice
          uri: lb://client-microservice
          predicates:
            - Path=/api/client/**

        - id: account-microservice
          uri: lb://account-microservice
          predicates:
            - Path=/api/account/**

        - id: bankdeposit-microservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/deposit/**

        - id: bankwithdrawal-microservice
          uri: http://localhost:8084
          predicates:
            - Path=/api/retire/**

        - id: bankcredit-microservice
          uri: lb://bankcredit-microservice
          predicates:
            - Path=/api/credit/**

        - id: creditcard-microservice
          uri: lb://creditcard-microservice
          predicates:
            - Path=/api/creditcard/**

        - id: transaction-microservice
          uri: lb://transaction-microservice
          predicates:
            - Path=/api/transaction/**

        - id: transfer-microservice
          uri: http://localhost:8086
          predicates:
            - Path=/api/transfer/**





