server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.7:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/client/**

        - id: accounts-microservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/account/**

        - id: bankdeposit-microservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/deposit/**

        - id: bankwithdrawal-microservice
          uri: http://localhost:8084
          predicates:
            - Path=/api/retire/**

        - id: bankcredit-microservice
          uri: http://localhost:8085
          predicates:
            - Path=/api/credit/**

        - id: creditcard-microservice
          uri: http://localhost:8088
          predicates:
            - Path=/api/creditcard/**

        - id: transaction-microservice
          uri: http://localhost:8087
          predicates:
            - Path=/api/transaction/**

        - id: transfer-microservice
          uri: http://localhost:8086
          predicates:
            - Path=/api/transfer/**





